### ISSUE TITLE
What about accounts that already had an authenticator linked before using this library?

### ISSUE THREAD

**Issue by FatherFoxxy** [geel9/SteamAuth#12] opened 2015-12-11 20:03 UTC
Out of curiosity, how would we save the file? It can never reach the step where the file is saved, for obvious reasons. Is this because Steam will only ever save the linked file once after linking mobile? Is the only available solution to unlink and relink using this library in order to capture the data?

**Comment by ChaosEmperor** [comment] 2015-12-13 03:21
If you try to add an authenticator to an account that already has one, the `AddAuthenticator()` method will return `GeneralFailure`.

The only solution would be to unlink and relink if you *have* to use this library. You could always manually extract the details from your phone to avoid the 7 day trade block.

**Comment by FatherFoxxy** [comment] 2015-12-13 03:26
Do you have a link on how to extract this data from a phone?

**Comment by ChaosEmperor** [comment] 2015-12-13 03:28
Never used it myself, but here you go : http://forums.backpack.tf/index.php?/topic/45995-guide-how-to-get-your-shared-secret-from-ios-device-steam-mobile/

**Comment by pipe01** [comment] 2015-12-14 13:43
If you wanna extract from an android phone, I'm developing  a fork of SteamDesktopAuthenticator which allows you to extract it, although it's still in development, and if anyone could help me, it would be greatly appreciated.

**Comment by ChaosEmperor** [comment] 2015-12-14 13:53
Not sure if this is the place to discuss this, but I may be able to help. What do you need?

**Comment by pipe01** [comment] 2015-12-14 13:58
Well, it can already extract a SteamGuardAccount object from the device, the issue is on the rest of the logic that is needed to implement that to the rest of the program. Also, the object that it extracts is missing the Session value, as it isn't contained on the json file. So that's where I'm stuck at the moment

**Comment by pipe01** [comment] 2015-12-14 13:59
I guess I should somehow generate it by making the user login.

**Comment by ChaosEmperor** [comment] 2015-12-14 15:34
I'm thoroughly familiar with the SteamAuth library with the exception of crypto, so AMA.

Alright, answering your question, session is not something that you should be concerned with extracting. A new session is created every time a user logs in. In your code, just leave session empty. It will be filled in when the user calls `DoLogin` in `UserLogin.cs`.

**Comment by pipe01** [comment] 2015-12-14 15:36
Oh, OK. I think I got it, thanks! I'm gonna test it when I get on my computer.

**Comment by ChaosEmperor** [comment] 2015-12-14 15:55
Let me know when you decide on a license. I would like to write a GUI based app for your library. Additionally, I plan to make the following changes :

# Remove unnecessary classes. Don't try to *replace* SteamAuth, but *complement* it.
# Provide simple but powerful GUI to allow users to extract their secrets easily.
# Add support for iOS devices at some point.

**Comment by pipe01** [comment] 2015-12-14 16:02
You mean my ADB.net?

**Comment by ChaosEmperor** [comment] 2015-12-14 16:15
I mean specifically a tool that enables users to extract their Steam secrets. If this requires your ADB.net library, then I will need your license for that as well.

**Comment by pipe01** [comment] 2015-12-14 16:18
Well, I can make a slim and adapted version of my library, or just use the class that is already in use on my fork. 
About ios, I have never in my life touched it and I have no idea on how the system even works.

**Comment by ChaosEmperor** [comment] 2015-12-14 16:23
I could create the new project right now and allow you write access if you'd like, so you can be a part of what it becomes.

iOS will not be that easy. It will require a root and SSH access if I'm not mistaken. I'm not very familiar with it as well, but I've been around it a couple of times.

**Comment by pipe01** [comment] 2015-12-14 16:25
That's fine by me! I can start developing either a few hours later or tomorrow.

**Comment by ChaosEmperor** [comment] 2015-12-14 16:32
Could I have your Steam so we can continue our discussion there without spamming this thread?

**Comment by Jessecar96** [comment] 2015-12-15 00:45
Fixed with #17

**Closed by Jessecar96** 2015-12-15 00:45 UTC
